package in.apoorv003.greendao.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import in.apoorv003.greendao.db.Movie;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MOVIE".
*/
public class MovieDao extends AbstractDao<Movie, Long> {

    public static final String TABLENAME = "MOVIE";

    /**
     * Properties of entity Movie.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Name = new Property(1, String.class, "name", false, "NAME");
        public final static Property MovieId = new Property(2, long.class, "movieId", false, "MOVIE_ID");
        public final static Property DirectorId = new Property(3, long.class, "directorId", false, "DIRECTOR_ID");
        public final static Property ProductionId = new Property(4, long.class, "productionId", false, "PRODUCTION_ID");
    };

    private DaoSession daoSession;

    private Query<Movie> director_MovieListQuery;
    private Query<Movie> productionHouse_MovieListQuery;

    public MovieDao(DaoConfig config) {
        super(config);
    }
    
    public MovieDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MOVIE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"NAME\" TEXT NOT NULL ," + // 1: name
                "\"MOVIE_ID\" INTEGER NOT NULL ," + // 2: movieId
                "\"DIRECTOR_ID\" INTEGER NOT NULL ," + // 3: directorId
                "\"PRODUCTION_ID\" INTEGER NOT NULL );"); // 4: productionId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MOVIE\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Movie entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getName());
        stmt.bindLong(3, entity.getMovieId());
        stmt.bindLong(4, entity.getDirectorId());
        stmt.bindLong(5, entity.getProductionId());
    }

    @Override
    protected void attachEntity(Movie entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Movie readEntity(Cursor cursor, int offset) {
        Movie entity = new Movie( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // name
            cursor.getLong(offset + 2), // movieId
            cursor.getLong(offset + 3), // directorId
            cursor.getLong(offset + 4) // productionId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Movie entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setName(cursor.getString(offset + 1));
        entity.setMovieId(cursor.getLong(offset + 2));
        entity.setDirectorId(cursor.getLong(offset + 3));
        entity.setProductionId(cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Movie entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Movie entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "movieList" to-many relationship of Director. */
    public List<Movie> _queryDirector_MovieList(long directorId) {
        synchronized (this) {
            if (director_MovieListQuery == null) {
                QueryBuilder<Movie> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.DirectorId.eq(null));
                director_MovieListQuery = queryBuilder.build();
            }
        }
        Query<Movie> query = director_MovieListQuery.forCurrentThread();
        query.setParameter(0, directorId);
        return query.list();
    }

    /** Internal query to resolve the "movieList" to-many relationship of ProductionHouse. */
    public List<Movie> _queryProductionHouse_MovieList(long productionId) {
        synchronized (this) {
            if (productionHouse_MovieListQuery == null) {
                QueryBuilder<Movie> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ProductionId.eq(null));
                productionHouse_MovieListQuery = queryBuilder.build();
            }
        }
        Query<Movie> query = productionHouse_MovieListQuery.forCurrentThread();
        query.setParameter(0, productionId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getDirectorDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getProductionHouseDao().getAllColumns());
            builder.append(" FROM MOVIE T");
            builder.append(" LEFT JOIN DIRECTOR T0 ON T.\"MOVIE_ID\"=T0.\"_id\"");
            builder.append(" LEFT JOIN PRODUCTION_HOUSE T1 ON T.\"MOVIE_ID\"=T1.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Movie loadCurrentDeep(Cursor cursor, boolean lock) {
        Movie entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Director director = loadCurrentOther(daoSession.getDirectorDao(), cursor, offset);
         if(director != null) {
            entity.setDirector(director);
        }
        offset += daoSession.getDirectorDao().getAllColumns().length;

        ProductionHouse productionHouse = loadCurrentOther(daoSession.getProductionHouseDao(), cursor, offset);
         if(productionHouse != null) {
            entity.setProductionHouse(productionHouse);
        }

        return entity;    
    }

    public Movie loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Movie> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Movie> list = new ArrayList<Movie>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Movie> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Movie> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
